pipeline {

    environment{
      REGISTRY = "raniamidaoui"
      IMAGE_NAME= "devops-lab-go-app-advanced"
      IMAGE_VERSION = "latest"
      LOGIN=credentials("sonar_login")
      SONARQUBE_URL="http://sonarqube:9000"
      PROJECT_KEY="devops-lab-go-app-advanced"
      REGISTRY_CRED = 'docker_creds'
      NETWORK = 'tools_jenkins'
      K8S_CONFIG_NAME="kubeconfig"
      K8S_NAMESPACE = 'default'
      K8S_DEPLOYMENT_NAME = "devops-lab-go-app-advanced"
    }

    tools {
      go 'go_114'
    }

    agent any
    
    stages {

        
        stage('SonarTests') {
            steps{
                script{
                    docker.image('sonarsource/sonar-scanner-cli').inside('-v /var/run/docker.sock:/var/run/docker.sock --entrypoint="" --net ${NETWORK}') {
                        sh "/opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.sources=. -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${LOGIN}"
                    }
                }
            }
        }

        stage("Build"){
            steps {
                echo "Docker Build"
                script{
                    dockerImg = docker.build("${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}", ".") 
                }
            }
            post{
                success{
                    echo "Build Successful"
                }
                failure{
                    echo "Build Failed"
                }
            }
        }
         
        stage("Push"){
            steps{
                script{
                    docker.withRegistry('', "${REGISTRY_CRED}") {
                        dockerImg.push()
                    }
                }
            }
            post{
                    success{
                        echo "Push Successful"
                    }
                    failure{
                        echo "Push Failed"
                    }
            }
        }

        stage('Deploy App') {
            steps {
                script{
                    docker.image('bitnami/kubectl').inside("--entrypoint=''  --net minikube"){
                        withKubeConfig([credentialsId: "$K8S_CONFIG_NAME", namespace: "$K8S_NAMESPACE"]) {
                            sh "kubectl -n \${K8S_NAMESPACE} rollout restart deployment.apps/\${K8S_DEPLOYMENT_NAME}"
                        }
                    }
                }                
            }
        }
        
    }


    post { 
        always { 
            cleanWs()
        }
    }
}